{
 "title": "Gitlab-backup",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "weekly_backups_total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weekly_backups_total{job=\"backup-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Changes weekly 7d",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(weekly_backups_total{job=\"backup-exporter\"}[7d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "monthly_backups_total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monthly_backups_total{job=\"backup-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Changes monthly 30d",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(monthly_backups_total{job=\"backup-exporter\"}[30d])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}